steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/gen-lang-client-0610398133/stockpulse/stockpulse-tracker:$COMMIT_SHA'
      - '-t'
      - 'us-west1-docker.pkg.dev/gen-lang-client-0610398133/stockpulse/stockpulse-tracker:latest'
      - '.'

  # Step 2: Push both tags to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-west1-docker.pkg.dev/gen-lang-client-0610398133/stockpulse/stockpulse-tracker']

  # Step 3: Deploy the new image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stockpulse-tracker'
      - '--image'
      - 'us-west1-docker.pkg.dev/gen-lang-client-0610398133/stockpulse/stockpulse-tracker:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--quiet'

images:
  - 'us-west1-docker.pkg.dev/gen-lang-client-0610398133/stockpulse/stockpulse-tracker'

options:
  logging: CLOUD_LOGGING_ONLY
